spring.application.name=obsystem
server.port=${PORT:8080}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Datasource padrao (Supabase Cloud) com suporte a variaveis de ambiente
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.uswcutkvvrsvjmbzucwv}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:KTStec!@#123}

# Hibernate DDL
spring.jpa.hibernate.ddl-auto=update

# Logs SQL
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}