spring.application.name=obsystem
server.port=8080

spring.profiles.active=local

# Manda o Hibernate criar as tabelas automaticamente sem apagar dados:
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL no console do Eclipse:
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true